name: dast-zap
on:
  push: { branches: ["main"] }
  pull_request: {}
  workflow_dispatch: {}

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker compose build
      - run: docker compose up -d
      - name: Wait for API
        run: for i in {1..30}; do curl -sf http://localhost:8080/ && break || sleep 2; done
      - name: ZAP full scan (JSON report)
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'http://localhost:8080/'
          cmd_options: '-a -m 3 -J reports/zap.json -w reports/zap.html'
          allow_issue_writing: false
          fail_action: false
      - name: Gate: fail if Medium/High alerts
        run: |
          test -f reports/zap.json || { echo "No ZAP JSON"; exit 1; }
          N=$(jq '[.site[].alerts[] | select((.riskcode|tonumber) >= 2)] | length' reports/zap.json)
          echo "ZAP Medium/High alerts: $N"
          if [ "$N" -gt 0 ]; then
            echo "❌ ZAP encontró $N alertas Medium/High"; exit 1
          fi
      - if: always()
        run: docker compose down
